import type { PropertyType, RoomType } from '@/lib/types';

// ============================================================
// PROPERTY TYPE DEFINITIONS
// ============================================================

export interface PropertyTypeOption {
  value: PropertyType;
  label: string;
  description: string;
  icon: string;
  defaultFloors: number;
  defaultBedrooms: number;
  defaultBathrooms: number;
}

export const PROPERTY_TYPES: PropertyTypeOption[] = [
  { value: 'studio_apartment', label: 'Studio Apartment', description: 'Open-plan compact living', icon: '🏢', defaultFloors: 1, defaultBedrooms: 0, defaultBathrooms: 1 },
  { value: '1bhk', label: '1 BHK', description: 'One bedroom apartment', icon: '🏠', defaultFloors: 1, defaultBedrooms: 1, defaultBathrooms: 1 },
  { value: '2bhk', label: '2 BHK', description: 'Two bedroom apartment', icon: '🏠', defaultFloors: 1, defaultBedrooms: 2, defaultBathrooms: 2 },
  { value: '3bhk', label: '3 BHK', description: 'Three bedroom apartment', icon: '🏠', defaultFloors: 1, defaultBedrooms: 3, defaultBathrooms: 3 },
  { value: '4bhk', label: '4 BHK', description: 'Four bedroom apartment', icon: '🏡', defaultFloors: 1, defaultBedrooms: 4, defaultBathrooms: 4 },
  { value: '5bhk', label: '5 BHK', description: 'Five bedroom apartment', icon: '🏡', defaultFloors: 1, defaultBedrooms: 5, defaultBathrooms: 5 },
  { value: '6plus_bhk', label: '6+ BHK', description: 'Six or more bedrooms', icon: '🏡', defaultFloors: 1, defaultBedrooms: 6, defaultBathrooms: 6 },
  { value: 'penthouse', label: 'Penthouse', description: 'Premium high-rise living', icon: '🌆', defaultFloors: 2, defaultBedrooms: 4, defaultBathrooms: 4 },
  { value: 'duplex', label: 'Duplex', description: 'Two-level apartment', icon: '🏘️', defaultFloors: 2, defaultBedrooms: 3, defaultBathrooms: 3 },
  { value: '2storey_villa', label: '2-Storey Villa', description: 'Two-floor independent villa', icon: '🏰', defaultFloors: 2, defaultBedrooms: 4, defaultBathrooms: 4 },
  { value: '3storey_villa', label: '3-Storey Villa', description: 'Three-floor luxury villa', icon: '🏰', defaultFloors: 3, defaultBedrooms: 5, defaultBathrooms: 5 },
  { value: 'independent_house', label: 'Independent House', description: 'Standalone residential property', icon: '🏡', defaultFloors: 2, defaultBedrooms: 3, defaultBathrooms: 3 },
  { value: 'farmhouse', label: 'Farmhouse', description: 'Rural or suburban estate', icon: '🌾', defaultFloors: 2, defaultBedrooms: 4, defaultBathrooms: 4 },
  { value: 'office', label: 'Office', description: 'Commercial workspace', icon: '🏢', defaultFloors: 1, defaultBedrooms: 0, defaultBathrooms: 2 },
  { value: 'retail', label: 'Retail', description: 'Retail or showroom space', icon: '🏪', defaultFloors: 1, defaultBedrooms: 0, defaultBathrooms: 1 },
  { value: 'hospitality', label: 'Hospitality', description: 'Hotel, restaurant, or lounge', icon: '🏨', defaultFloors: 1, defaultBedrooms: 0, defaultBathrooms: 2 },
  { value: 'custom', label: 'Custom Property', description: 'Define your own property type', icon: '✏️', defaultFloors: 1, defaultBedrooms: 0, defaultBathrooms: 0 },
];

// ============================================================
// DEFAULT ROOM GENERATION TEMPLATES
// ============================================================

export interface DefaultRoom {
  name: string;
  room_type: RoomType;
  floor: number; // 0 = ground, 1 = first, etc.
}

export const PROPERTY_ROOM_TEMPLATES: Record<string, DefaultRoom[]> = {
  studio_apartment: [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Living Area', room_type: 'living_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Bathroom', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
  ],
  '1bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Bedroom', room_type: 'bedroom', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Bathroom', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
  ],
  '2bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Area', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 0 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 0 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 0 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
    { name: 'Utility Area', room_type: 'utility', floor: 0 },
  ],
  '3bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Area', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 0 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 0 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 0 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
    { name: 'Utility Area', room_type: 'utility', floor: 0 },
  ],
  '4bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Room', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 0 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 4', room_type: 'bedroom', floor: 0 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 0 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 4', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony 1', room_type: 'balcony', floor: 0 },
    { name: 'Balcony 2', room_type: 'balcony', floor: 0 },
    { name: 'Study', room_type: 'study', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
    { name: 'Utility Area', room_type: 'utility', floor: 0 },
  ],
  '5bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Family Lounge', room_type: 'family_lounge', floor: 0 },
    { name: 'Dining Room', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 0 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 4', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 5', room_type: 'bedroom', floor: 0 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 0 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 4', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 5', room_type: 'bathroom', floor: 0 },
    { name: 'Balcony 1', room_type: 'balcony', floor: 0 },
    { name: 'Balcony 2', room_type: 'balcony', floor: 0 },
    { name: 'Study', room_type: 'study', floor: 0 },
    { name: 'Puja Room', room_type: 'puja_room', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
    { name: 'Utility Area', room_type: 'utility', floor: 0 },
  ],
  '6plus_bhk': [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Grand Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Family Lounge', room_type: 'family_lounge', floor: 0 },
    { name: 'Formal Dining', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Master Suite', room_type: 'master_bedroom', floor: 0 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 4', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 5', room_type: 'bedroom', floor: 0 },
    { name: 'Bedroom 6', room_type: 'bedroom', floor: 0 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 0 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 4', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 5', room_type: 'bathroom', floor: 0 },
    { name: 'Bathroom 6', room_type: 'bathroom', floor: 0 },
    { name: 'Study', room_type: 'study', floor: 0 },
    { name: 'Home Theatre', room_type: 'home_theatre', floor: 0 },
    { name: 'Puja Room', room_type: 'puja_room', floor: 0 },
    { name: 'Gym', room_type: 'gym', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
    { name: 'Utility Area', room_type: 'utility', floor: 0 },
    { name: 'Servant Room', room_type: 'servant_room', floor: 0 },
  ],
  '2storey_villa': [
    // Ground Floor
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Room', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Guest Bedroom', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Guest Bathroom', room_type: 'guest_bathroom', floor: 0 },
    { name: 'Powder Room', room_type: 'powder_room', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Parking', room_type: 'parking', floor: 0 },
    { name: 'Garden', room_type: 'garden', floor: 0 },
    // First Floor
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 1 },
    { name: 'Family Lounge', room_type: 'family_lounge', floor: 1 },
    { name: 'Balcony', room_type: 'balcony', floor: 1 },
    { name: 'Passage', room_type: 'passage', floor: 1 },
    { name: 'Staircase', room_type: 'staircase', floor: 1 },
  ],
  '3storey_villa': [
    // Ground Floor
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Grand Foyer', room_type: 'foyer', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Formal Dining', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Guest Bedroom', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Guest Bathroom', room_type: 'guest_bathroom', floor: 0 },
    { name: 'Powder Room', room_type: 'powder_room', floor: 0 },
    { name: 'Study', room_type: 'study', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Parking', room_type: 'parking', floor: 0 },
    { name: 'Garden', room_type: 'garden', floor: 0 },
    // First Floor
    { name: 'Master Suite', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Bathroom 3', room_type: 'bathroom', floor: 1 },
    { name: 'Family Lounge', room_type: 'family_lounge', floor: 1 },
    { name: 'Balcony', room_type: 'balcony', floor: 1 },
    { name: 'Passage', room_type: 'passage', floor: 1 },
    { name: 'Staircase', room_type: 'staircase', floor: 1 },
    // Second Floor
    { name: 'Bedroom 4', room_type: 'bedroom', floor: 2 },
    { name: 'Bedroom 5', room_type: 'bedroom', floor: 2 },
    { name: 'Bathroom 4', room_type: 'bathroom', floor: 2 },
    { name: 'Bathroom 5', room_type: 'bathroom', floor: 2 },
    { name: 'Home Theatre', room_type: 'home_theatre', floor: 2 },
    { name: 'Gym', room_type: 'gym', floor: 2 },
    { name: 'Terrace', room_type: 'terrace', floor: 2 },
    { name: 'Passage', room_type: 'passage', floor: 2 },
  ],
  penthouse: [
    // Lower Level
    { name: 'Private Lobby', room_type: 'entrance', floor: 0 },
    { name: 'Grand Living', room_type: 'living_room', floor: 0 },
    { name: 'Dining Room', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Guest Suite', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Guest Bathroom', room_type: 'guest_bathroom', floor: 0 },
    { name: 'Powder Room', room_type: 'powder_room', floor: 0 },
    { name: 'Study', room_type: 'study', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
    // Upper Level
    { name: 'Master Suite', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Family Lounge', room_type: 'family_lounge', floor: 1 },
    { name: 'Home Theatre', room_type: 'home_theatre', floor: 1 },
    { name: 'Terrace', room_type: 'terrace', floor: 1 },
  ],
  duplex: [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Area', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Powder Room', room_type: 'powder_room', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Balcony', room_type: 'balcony', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Passage', room_type: 'passage', floor: 1 },
  ],
  independent_house: [
    { name: 'Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Living Room', room_type: 'living_room', floor: 0 },
    { name: 'Dining Room', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Guest Bedroom', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Guest Bathroom', room_type: 'guest_bathroom', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Parking', room_type: 'parking', floor: 0 },
    { name: 'Master Bedroom', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Balcony', room_type: 'balcony', floor: 1 },
    { name: 'Passage', room_type: 'passage', floor: 1 },
  ],
  farmhouse: [
    { name: 'Main Entrance', room_type: 'entrance', floor: 0 },
    { name: 'Grand Living', room_type: 'living_room', floor: 0 },
    { name: 'Dining Hall', room_type: 'dining_room', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Guest Suite 1', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Guest Suite 2', room_type: 'guest_bedroom', floor: 0 },
    { name: 'Bathroom', room_type: 'bathroom', floor: 0 },
    { name: 'Staircase', room_type: 'staircase', floor: 0 },
    { name: 'Garden', room_type: 'garden', floor: 0 },
    { name: 'Pool Area', room_type: 'pool', floor: 0 },
    { name: 'Outdoor Area', room_type: 'outdoor', floor: 0 },
    { name: 'Parking', room_type: 'parking', floor: 0 },
    { name: 'Master Suite', room_type: 'master_bedroom', floor: 1 },
    { name: 'Bedroom 2', room_type: 'bedroom', floor: 1 },
    { name: 'Bedroom 3', room_type: 'bedroom', floor: 1 },
    { name: 'Master Bathroom', room_type: 'master_bathroom', floor: 1 },
    { name: 'Bathroom 2', room_type: 'bathroom', floor: 1 },
    { name: 'Terrace', room_type: 'terrace', floor: 1 },
  ],
  office: [
    { name: 'Reception', room_type: 'entrance', floor: 0 },
    { name: 'Conference Room', room_type: 'living_room', floor: 0 },
    { name: 'Open Workspace', room_type: 'living_room', floor: 0 },
    { name: 'Private Office 1', room_type: 'study', floor: 0 },
    { name: 'Private Office 2', room_type: 'study', floor: 0 },
    { name: 'Pantry', room_type: 'kitchen', floor: 0 },
    { name: 'Washroom 1', room_type: 'bathroom', floor: 0 },
    { name: 'Washroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Server Room', room_type: 'utility', floor: 0 },
    { name: 'Passage', room_type: 'passage', floor: 0 },
  ],
  retail: [
    { name: 'Storefront', room_type: 'entrance', floor: 0 },
    { name: 'Display Area', room_type: 'living_room', floor: 0 },
    { name: 'Storage', room_type: 'store_room', floor: 0 },
    { name: 'Office', room_type: 'study', floor: 0 },
    { name: 'Washroom', room_type: 'bathroom', floor: 0 },
  ],
  hospitality: [
    { name: 'Lobby', room_type: 'entrance', floor: 0 },
    { name: 'Main Hall', room_type: 'living_room', floor: 0 },
    { name: 'VIP Lounge', room_type: 'family_lounge', floor: 0 },
    { name: 'Kitchen', room_type: 'kitchen', floor: 0 },
    { name: 'Washroom 1', room_type: 'bathroom', floor: 0 },
    { name: 'Washroom 2', room_type: 'bathroom', floor: 0 },
    { name: 'Office', room_type: 'study', floor: 0 },
    { name: 'Outdoor Area', room_type: 'outdoor', floor: 0 },
  ],
  custom: [],
};

// ============================================================
// PROJECT STATUS OPTIONS
// ============================================================

export const PROJECT_STATUS_OPTIONS = [
  { value: 'planning', label: 'Planning Stage' },
  { value: 'construction_started', label: 'Construction Started' },
  { value: 'electrical_in_progress', label: 'Electrical Work in Progress' },
  { value: 'interior_in_progress', label: 'Interior Work in Progress' },
  { value: 'nearly_completed', label: 'Nearly Completed' },
  { value: 'ready', label: 'Ready Property' },
  { value: 'occupied', label: 'Occupied Property' },
  { value: 'renovation', label: 'Renovation' },
] as const;

export const AUTOMATION_TYPE_OPTIONS = [
  { value: 'new_construction', label: 'New Construction' },
  { value: 'retrofit', label: 'Retrofit Existing Home' },
  { value: 'partial_renovation', label: 'Partial Renovation' },
  { value: 'not_sure', label: 'Not Sure' },
] as const;

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya',
  'Mizoram', 'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim',
  'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
  'West Bengal', 'Delhi', 'Chandigarh', 'Puducherry', 'Jammu and Kashmir',
  'Ladakh',
] as const;
